name: Update Coverage in README
on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!master" # excludes master

jobs:
  Format_and_Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    name: Node ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Format and Check code
        run: pnpm fc
  Jest_Test:
    runs-on: ubuntu-latest
    needs: Format_and_Check
    strategy:
      matrix:
        node-version: [16.x, 20.x]
    name: Test with Jest Node ${{ matrix.node-version }}
    steps:
      - name: Create DB
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: root
          mysql database: "pakaiwa"
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: create .env
        run: mv .env.example .env
      - name: Install dependencies
        run: pnpm i
      - name: Migration
        run: pnpm mig
      - name: Seed
        run: pnpm seed
      - name: Test
        run: pnpm test
  Create_Test_Coverage_Badges:
    runs-on: ubuntu-latest
    needs: Format_and_Check
    name: Test with Jest Node 18.x LTS
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: root
          mysql database: "pakaiwa"
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: create .env
        run: mv .env.example .env
      - name: Install dependencies
        run: pnpm i
      - name: Migration
        run: pnpm mig
      - name: Seed
        run: pnpm seed
      - name: Test
        run: pnpm test
      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-summary: true
          coverage-summary-path: ./coverage/coverage-summary.json

      - name: Update README with Coverage HTML
        run: |
          sed -i '/<!-- Jest Coverage Comment:Begin -->/,/<!-- Jest Coverage Comment:End -->/c\<!-- Jest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.summaryHtml }}\n<!-- Jest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes in README
        uses: actions-js/push@master
        with:
          message: Update coverage in README
          github_token: ${{ secrets.GH_TOKEN }}
