name: Unit Test 🧪

on:
  push:
    branches: ["main", "dev", "qa"]
  pull_request:
    branches: ["main", "dev", "qa"]

jobs:
  Format_and_Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [canary, 1.0.x, 1.1.x]
    name: Node ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Use Bun ${{ matrix.node-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: bun i
      - name: Format and Check code
        run: bun run fc
  Jest_Test:
    runs-on: ubuntu-latest
    needs: Format_and_Check
    strategy:
      matrix:
        node-version: [canary, 1.0.x]
    name: Test with Jest Bun ${{ matrix.node-version }}
    steps:
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS pakaiwa;" -uroot -proot
      - uses: actions/checkout@v4.1.6
      - name: Use Bun ${{ matrix.node-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.node-version }}
      - name: create .env
        run: mv .env.example .env
      - name: Install dependencies
        run: pnpm i
      - name: Migration
        run: bun run mig
      - name: Seed
        run: bun run seed
      - name: Test
        run: bun run test
  Create_Test_Coverage_Badges:
    runs-on: ubuntu-latest
    needs: Format_and_Check
    name: Test with Jest Bun Latest
    steps:
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS pakaiwa;" -uroot -proot
      - uses: actions/checkout@v4.1.6
      - name: Setup Node.js environment
        uses: oven-sh/setup-bun@v2
      - name: create .env
        run: mv .env.example .env
      - name: Install dependencies
        run: bun i
      - name: Migration
        run: bun run mig
      - name: Seed
        run: bun run seed
      - name: Test
        run: bun run test
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@v1.9.18
        with:
          branches: main,dev
