name: Unit Test 🧪

on:
  push:
    branches: ["main", "dev", "qa"]
  pull_request:
    branches: ["main", "dev", "qa"]

jobs:
  Format_and_Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    name: Node ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Format and Check code
        run: pnpm fc
  Jest_Test:
    runs-on: ubuntu-latest
    needs: Format_and_Check
    strategy:
      matrix:
        node-version: [18.x, 22.x]
    name: Test with Jest Node ${{ matrix.node-version }}
    steps:
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS pakaiwa;" -uroot -proot
      - uses: actions/checkout@v4.1.6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: create .env
        run: mv .env.example .env
      - name: Install dependencies
        run: pnpm i
      - name: Migration
        run: pnpm mig
      - name: Seed
        run: pnpm seed
      - name: Test
        run: pnpm test
  Create_Test_Coverage_Badges:
    runs-on: ubuntu-latest
    needs: Format_and_Check
    name: Test with Jest Node 20.x LTS
    steps:
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS pakaiwa;" -uroot -proot
      - uses: actions/checkout@v4.1.6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: create .env
        run: mv .env.example .env
      - name: Install dependencies
        run: pnpm i
      - name: Migration
        run: pnpm mig
      - name: Seed
        run: pnpm seed
      - name: Test
        run: pnpm test
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@v1.9.18
        with:
          branches: main,dev
